-- Add migration script here
ALTER TYPE edit_format
RENAME VALUE 'IMAX-VIDEO' TO 'IMAX';
ALTER TYPE edit_format
RENAME VALUE 'ACADEMY-VIDEO' TO 'ACADEMY';
ALTER TYPE edit_format
RENAME VALUE 'SQUARE-VIDEO' TO 'SQUARE';
ALTER TYPE edit_format
RENAME VALUE 'VERTICAL-VIDEO' TO 'VERTICAL';
ALTER TYPE poster_format
RENAME VALUE 'CANVAS-POSTER' TO 'CANVAS';
ALTER TYPE poster_format
RENAME VALUE 'STANDARD-POSTER' TO 'STANDARD';
ALTER TYPE poster_format
RENAME VALUE 'SQUARE-POSTER' TO 'SQUARE';
ALTER TYPE poster_format
RENAME VALUE 'VERTICAL-POSTER' TO 'VERTICAL';
CREATE TABLE work_views(
  work_id UUID NOT NULL,
  profile_id UUID NOT NULL,
  times_watched BIGINT DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW (),
  PRIMARY KEY (work_id, profile_id),
  CONSTRAINT fk_work FOREIGN KEY (work_id) REFERENCES works (id) ON DELETE CASCADE,
  CONSTRAINT fk_profile FOREIGN KEY (profile_id) REFERENCES profiles (id) ON DELETE CASCADE
);
CREATE TABLE work_likes(
  work_id UUID NOT NULL,
  profile_id UUID NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW (),
  PRIMARY KEY (work_id, profile_id),
  CONSTRAINT fk_work FOREIGN KEY (work_id) REFERENCES works (id) ON DELETE CASCADE,
  CONSTRAINT fk_profile FOREIGN KEY (profile_id) REFERENCES profiles (id) ON DELETE CASCADE
);
ALTER TABLE originals
ADD COLUMN category original_category NOT NULL DEFAULT 'MOVIE';
ALTER TABLE episodes
  RENAME COLUMN original_id TO series_id;
ALTER TABLE ledger
ADD CONSTRAINT fk_episode FOREIGN KEY (episode_id) REFERENCES episodes (id) ON DELETE
SET NULL;